[package]
name = "sv_extractor"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
clap = { version = "4.0.26", features = ["derive"] }
ooz-sys = "0.2.0"
flatbuffers = "22.10.26"
